eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${http://host.docker.internal:8761/eureka/:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
