eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://host.docker.internal:8761,http://localhost:8761}
    fetch-registry: true
    register-with-eureka: true
